version: '3.8'

services:
  oxygennet:
    build: .
    image: oxygennet:1.0.0
    container_name: oxygennet
    restart: unless-stopped
    ports:
      - "8787:8787"
    volumes:
      - ./configs:/app/configs
    environment:
      - API_ID=your_telegram_api_id
      - API_HASH=your_telegram_api_hash
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"